[project]
name = "fortuna"
version = "1.0.0"
description = "телеграм бот с мини играми"
authors = [
    {name = "aaafeig",email = "geroy.ozhog08@mail.ru"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "telebot (>=0.0.5,<0.0.6)",
    "black (>=25.1.0,<26.0.0)",
    "flake8 (>=7.2.0,<8.0.0)",
    "python-dotenv (>=1.1.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[black]
line-length = 119
exclude = ".git"
